FROM java:openjdk-8u111-jdk-alpine

RUN apk add --no-cache curl

COPY target/message-processor-1.0-SNAPSHOT.jar /usr/local/bin/message-processor.jar
COPY etc/staging.properties /usr/local/etc/message-processor/staging.properties

ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/local/bin/message-processor.jar", "/usr/local/etc/message-processor/staging.properties"]
